apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expense-app
    version: v1
  name: expense-app-v1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-app
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expense-app
        version: v1
    spec:
      containers:
      - image: yogananddocker/expense-app:0.0.1.RELEASE
        imagePullPolicy: Always
        name: expense-app
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: expense-app
  name: expense-app
  namespace: default
spec:
  ports:
    - nodePort: 32026
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: expense-app
  sessionAffinity: None
  type: LoadBalancer
